In [1]:
import torch

In [2]:
tensorX = torch.tensor([1, 2, 3, 4])
print(torch.unsqueeze(tensorX, 1))
tensorX = torch.tensor([1, 2, 3, 4])
torch.unsqueeze(tensorX, 1)

tensor([[1],
        [2],
        [3],
        [4]])


tensor([[1],
        [2],
        [3],
        [4]])

In [4]:
new_tensor = torch.tensor([[1.0, 2.0], [3.0, 4.0]])  # invertir el resultado
torch.mean(new_tensor, dim=1), torch.mean(new_tensor, dim=0), torch.mean(new_tensor)

(tensor([1.5000, 3.5000]), tensor([2., 3.]), tensor(2.5000))

#### clasificador de imágenes 
cat | cat

### Stochastic Gradient Descent
#### El Descenso de gradiente estocástico (SGD) 
***
- Es un enfoque simple pero muy eficiente para el aprendizaje discriminativo de clasificadores lineales bajo funciones de pérdida convexa como Máquinas de vectores de soporte (lineales) y Regresión logística.
- Tal vez sea más eficiente elegir ejemplos
aleatorios.
- Un solo ejemplo es muy poco, trabajamos con un batch.
- calcula el gradiante usando una sola muestra

### Mini Batch Stochastic Gradient Descent
#### El descenso de gradiente de mini lotes 
***
- Es una variación del algoritmo de descenso de gradiente que divide el conjunto de datos de entrenamiento en pequeños lotes que se utilizan para calcular el error del modelo y actualizar los coeficientes del modelo.
- calcula el gradiante usando varias muestras

### Full-Batch Gradient Descent
- calcula el gradiante usando todo el conjunto de datos

| Regresión | Clasificación |
| -- | -- |
| predecir cantidates | categorías |

#### Supervised ML:
 - features
 - labels

### Sigmoide
unos y ceros

### loss.backwark()
- backpropagation
  - que lo que estamos prediciendo tenga sentido
  - la conexión en código que va a ir:
    - primero hacia adelante
    - luego, regresamos para arreglar algo
    - volvemos a ir hacia adelante
- train loop

### optimizer.step()
- mover el loop
- vinculado a los gradiantes
- loss funtion, de la perdida en base de la predicción y el dato real
- luego repetimos con nuevos valores hasta que logremos un minimo
### optimizer.zero_grad()
reiniciar los gradiantes acumulados
### Foward pass
va a ver una predición

### función de activación en las neuronas de una NN
- La función de activación que convierte las entradas ponderadas de una neurona a su activación a la salida.
- La función de activación se encarga de devolver una salida a partir de un valor de entrada, normalmente el conjunto de valores de salida en un rango determinado como (0,1) o (-1,1).
- Cada neurona tiene una función de activación y nos va a permitir conectar las múltiples capas para realizar la transformación de lineal a red neuronal
- NN nos permite solucionar problemas no-lineales
***
- introduce no linealidad al input y el output

### DataLoader
- Cargar datos en un tamaño
- Cada **bath** depende el tamaño dado a iterar
- Carga una valuidación de datos
- Proporciona una iterativo sobre el conjunto de datos | esta es la respuesta
- **shuffle**, reorganiza los datos en cada epoch su es True
***
- En el clasificador de imágenes se implementa para dar un efectivo *Accuracy* en la validación de los datos